### ISSUE TITLE
Can't use PHP 7.4 and MYSQL 5.7 container version

### ISSUE THREAD

**Issue by ronangr1** [Wamoco/magedev#3]
Hi, 

I'm facing an issue with Magedev.

When I try to use php 7.4 and mysql 5.7 version (in the magedev.json), I get an error from my OS (java error) and there is no way to connect to the mysql container.

My magedev.json file

```
{
  "magento_version": "2",
  "domain": "dev.magento.local",
  "source_folder": "magento/",
  "php_version": "7.4",
  "mysql_version": "5.7",
  "dump_file": "path/to/mysql/dump.sql",
  "xdebug": {
    "idekey": "PHPSTORM"
  }
}
```
OS : Fedora 37
Docker version: 23.0.1, build a5ee5b1

Thanks a lot

**Comment by bka** [comment]
We never tested on Fedora. What error message do you get?
